################################################################################
# Site setup
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://samui-samui.de/"       # hostname & path to the root
defaultContentLanguage = "de"
disableHugoGeneratorInject = true         # we do that proudly on each page in the footer. visible.
enableEmoji = true                        # see https://www.webfx.com/tools/emoji-cheat-sheet/
# dev: check https://discourse.gohugo.io/t/differing-pages-between-dev-and-production/28270
#    before enabling this.
enableGitInfo = false                     # Enable GitInfo feature
enableRobotsTXT = true                    # Build robots.txt file
footnoteAnchorPrefix = "#"
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-17376057-1"
languageCode = "de_DE"
languageName = "Deutsch"
logFile = "hugo.log"
paginate = 5                              # default 5 items per page
paginatePath = "seite"
relativeURLs = true                       # makes all relative urls absolute to root... yeah, don't ask. we won't tell...
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/404.html"
rssLimit = 10
summaryLength = 150                       # the length of text to show in a .Summary
title = "Samui? Samui!"
verbose = false
verboseLog = true

################################################################################
# Bugfixes and Troubleshooting
################################################################################
# workaround for time out error on netlify
# "Error building site: $FILENAME: timed out initializing value. This is most likely a circular loop in a shortcode"
timeout = "30000"

################################################################################
# Output formats and structure
################################################################################
# see http://gohugo.io/templates/output-formats/
# see https://gohugo.io/news/http2-server-push-in-hugo/
[outputs]
home = [ "HTML", "RSS", "Algolia", "REDIR", "HEADERS" ]
page = [ "HTML" ]
post = [ "HTML" ]

[outputFormats]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true


[taxonomies]
tag = "tags"
leute = "leute"
feiertag = "feiertage"

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

################################################################################
# Sitemap
################################################################################
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.8

################################################################################
# Author
################################################################################
[author]
name = "Patrick Kollitsch"
homepage = "https://kollitsch.de/"

################################################################################
# Menue points without local page
################################################################################
[[menu.main]]
name = "DNB"
weight = 250
identifier = "dnb"
url = "https://davids-neighbour.com"
pre = "icons/user-tie.svg"
