################################################################################
# Module setup
## [module]
################################################################################
# see
# https://gohugo.io/hugo-modules/configuration/#module-config-imports
################################################################################
[[imports]]
path = "github.com/dnb-org/components/netlification"
disabled = false

[[imports]]
path = "github.com/dnb-org/garuda"
disabled = false
