[[imports]]
path = "github.com/dnb-hugo/components/netlification"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/garuda"
disabled = false

[[imports]]
path = "github.com/dnb-hugo/components/favicon"
disabled = false

[[module.imports]]
path = "github.com/dnb-hugo/debugprint"
disabled = false
