################################################################################
# Module setup
## [module]
################################################################################
# see
# https://gohugo.io/hugo-modules/configuration/#module-config-imports
################################################################################
[[imports]]
path = "github.com/davidsneighbour/hugo-auditor"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-netlification"
disabled = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-opensearch"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-pwa"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-robots"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-search-algolia"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-sitemap"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-social"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-hooks"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/libraries/bootstrap-icons"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/libraries/dayjs"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/libraries/lazysizes"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-shortcodes"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-youtube"
disable = false
ignoreConfig = false
ignoreImports = false
