################################################################################
# Module setup
## [module]
################################################################################
# see
# https://gohugo.io/hugo-modules/configuration/#module-config-imports
################################################################################
replacements = "github.com/davidsneighbour/hugo-social -> ../../hugo-social"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/auditor"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/head"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/netlification"
disabled = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/opensearch"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/pwa"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/robots"
disable = false
ignoreConfig = false
ignoreImports = false

# [[imports]]
# path = "github.com/davidsneighbour/hugo-modules/modules/search-algolia"
# disable = false
# ignoreConfig = false
# ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/sitemap"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/social"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/icons"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/libraries/dayjs"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/libraries/lazysizes"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/shortcodes"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/youtube"
disable = false
ignoreConfig = false
ignoreImports = false
