[Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[OpenSearch]
mediatype = "application/opensearchdescription+xml"
baseName = "opensearch"
isPlainText = true
notAlternative = true

[manifest]
name = "manifest"
baseName = "manifest"
mediaType = "text/webmanifest"
isPlainText = true
notAlternative = true
permalinkable = true
