################################################################################
# Site parameters
## [params]
################################################################################
# see
# https://gohugo.io/variables/site/#the-siteparams-variable
################################################################################
debug = false
mainSections = ["posts"]

# social media setup
og_image = ""
og_image_url = ""
githubName = ""

# content particles
siteslug = "samui-samui-de"
description = "David's Neighbour's Notizen über sein Leben als Auswanderer auf der Insel Koh Samui in Thailand. Auf Deutsch, und so..."
copyright = "All rights reserved. Copyright samui-samui.de"

# design elements
sitecolor = "#d02d19"

[imaging]
sizes = ["825","610","510","450"]

#############################################################
# Search Setup
#############################################################
[algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[opensearch]
# https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md

#############################################################
# Social Media Setup
#############################################################
[social.facebook]
profileid = "517050641"    # patrick.kollitsch
pageid = "6967849771"      # samuisamui
appid = "2047624572136513" # samui-samui.de
profileslug = "patrick.kollitsch"

[social.twitter]
profileid = "davidsneighbour"
siteid = "samui2"
theme ="dark"
linkcolor = "#d02d19"
dnt = "on"
csp = "on"

[social.snapchat]
profileid = "pkollitsch"

[social.whatsapp]
profileid = "66878979350"

#############################################################
# DNB Hugo Garuda Setup
#############################################################
[dnb]
theme_slug = "samui-samui"
javascript = "local-changes.js"
copy-from = "2005"

[dnb.sidebar]
enabled = true
items = [ "author", "archive", "recent", "social" ]
[dnb.sidebar.author]
content = "authorfooter"
[dnb.sidebar.recent]
limit = 5
[dnb.sidebar.social]
[dnb.sidebar.archive]
[dnb.sidebar.radio]
spotify_playlist = "https://open.spotify.com/embed/playlist/7DEuLS0qC7ajP84kEuWw6H"

[dnb.footer.index]
enabled = true
items = [ "tagcloud", "leutecloud" ]
[dnb.footer.single]
enabled = false
[dnb.footer.tagcloud]
enabled = true
type = "cloud"
values = "tags"

[dnb.footer.leutecloud]
enabled = true
type = "cloud"
values = "leute"

[dnb.comments]
#repo = "davidsneighbour/samui-samui.de.comments"
# src = "https://utteranc.es/client.js"
# term = "pathname"
# label = "💬"
# theme = "github-dark-orange"

[dnb.algolia]
appId = "166C265UOG"
apiKey = "7e52bca82b03b3a7eb6bbee9fa7429f3"
indexName = "samui-samui-de"
numberLocale = "de"

################################################################################
# hugo-head @see https://github.com/davidsneighbour/hugo-head
################################################################################
[dnb.head]
charset = "utf-8"
viewport = "width=device-width, initial-scale=1"
latitude = "9.578492"
longitude = "99.958311"
# https://en.wikipedia.org/wiki/ISO_3166
region = "TH-84"
placename = "Koh Samui"
separator = " ↭ "
disable = []
notranslate = false     # tell Google not to provide a translation for this document
# https://webmonetization.org/docs/getting-started
monetization = ""

[dnb.head.speedoptimisation]
control = "on" # on/off - off disables all prefetching
prefetch = [
  "/assets/webfonts/tomkin/Tomkin/TomkinLight/Tomkin-Light.woff",
  "/assets/webfonts/tomkin/Tomkin/TomkinSemiLight/Tomkin-SemiLight.woff",
]
preconnect = []
prerender = []

[dnb.head.verification]
google = ""
yandex = ""
bing = ""
alexa = ""
pinterest = ""
norton = ""

[dnb.head.styles]
method = "postcss"

[dnb.head.styles.options]
# options for the compilation of CSS
# see https://gohugo.io/hugo-pipes/scss-sass/#options
#transpiler = "dartsass"
outputStyle = "compressed"
targetPath = "theme.css"
enableSourceMap = true
includePaths = ["node_modules/"]
