################################################################################
# Related posts
################################################################################
threshold = 80 # Only include matches with rank >= threshold. 0 and 100.
includeNewer = true # adding newer articles to older ones (changing the content)
toLower = true # Will lower case keywords in both queries and in the indexes.

[[indices]]
name  = "tags"
weight = 100

[[indices]]
name  = "date"
weight = 10
pattern = "2006" # “200601” for busier times?
