################################################################################
# configuration for BOT https://github.com/JasonEtco/todo
################################################################################
todo:
  keyword:
    - @todo
    - TODO
  bodyKeyword:
    - @body
    - BODY
  blobLines:   50
  autoAssign:  'davidsneighbour'
  label:       ['todo']
