#############################################################
# Site setup
# see https://gohugo.io/getting-started/configuration/
#############################################################
baseURL = "https://samui-samui.de/"       # hostname & path to the root
defaultContentLanguage = "de"
disableHugoGeneratorInject = true         # we do that proudly on each page in the footer. visible.
enableEmoji = true                        # see https://www.webfx.com/tools/emoji-cheat-sheet/
# dev: check https://discourse.gohugo.io/t/differing-pages-between-dev-and-production/28270
#    before enabling this.
enableGitInfo = false                     # Enable GitInfo feature
enableRobotsTXT = true                    # Build robots.txt file
footnoteAnchorPrefix = "#"
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-17376057-1"
languageCode = "de_DE"
languageName = "Deutsch"
logFile = "hugo.log"
paginate = 5                              # default 5 items per page
paginatePath = "seite"
relativeURLs = true                       # makes all relative urls absolute to root... yeah, don't ask. we won't tell...
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/404.html"
rssLimit = 10
summaryLength = 150                       # the length of text to show in a .Summary
title = "Samui? Samui!"
verbose = false
verboseLog = true

##################################################################################
# Bugfixes and Troubleshooting
##################################################################################
# workaround for time out error on netlify
# "Error building site: $FILENAME: timed out initializing value. This is most likely a circular loop in a shortcode"
timeout = "30000"

##################################################################################
# Blackfriday configuration
# see https://gohugo.io/getting-started/configuration/#blackfriday-options
##################################################################################
[blackfriday]
nofollowLinks = true
noreferrerLinks = true
plainIDAnchors = true
extensions = [
  "laxHtmlBlocks", # laxer block handling... let's see what this does?
  # "hardLineBreak", # newlines result in line breaks
]

[languages]
[languages.de]
weight = 1

##################################################################################
# Output formats and structure
##################################################################################
# see http://gohugo.io/templates/output-formats/
# see https://gohugo.io/news/http2-server-push-in-hugo/
[outputs]
home = [ "HTML", "RSS", "Algolia", "REDIR", "HEADERS" ]
page = [ "HTML" ]
post = [ "HTML" ]

[outputFormats]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# see https://gohugo.io/content-management/urls/
[permalinks]
  posts = "/:year/:month/:slug/"
  leute = "/:section/:slug/"
  tags = "/:section/:slug/"

[taxonomies]
  tag = "tags"
  leute = "leute"
  feiertag = "feiertage"

[mediaTypes]
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

#############################################################
# Sitemap
#############################################################
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

#############################################################
# Author
#############################################################
[author]
  name = "Patrick Kollitsch"
  homepage = "https://kollitsch.de/"

#############################################################
# Privacy setup
#############################################################
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
    disableInlineCSS = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

#############################################################
# Imaging setup
#############################################################
[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "lanczos"
  # Default JPEG quality setting. Default is 75.
  quality = 85
  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"

[params.imaging]
  sizes = ["825","610","510","450"]

#############################################################
# Menue points without local page
#############################################################
[[menu.main]]
  name = "DNB"
  weight = 250
  identifier = "dnb"
  url = "https://davids-neighbour.com"
  pre = "icons/user-tie.svg"

#############################################################
# Related posts
#############################################################
[related]
  threshold = 80 # Only include matches with rank >= threshold. 0 and 100.
  includeNewer = true # adding newer articles to older ones (changing the content)
  toLower = true # Will lower case keywords in both queries and in the indexes.

[[related.indices]]
  name  = "tags"
  weight = 100

[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006" # “200601” for busier times?

[module]

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/netlification"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo-garuda"

#############################################################
# Site params
#############################################################
[params]
  version = "2019.2.159"
  debug = false
  mainSections = ["posts"]

  # social media setup
  og_image = ""
  og_image_url = ""
  githubName = ""

  # content particles
  siteslug = "samui-samui-de"
  description = "David's Neighbour's Notizen über sein Leben als Auswanderer auf der Insel Koh Samui in Thailand. Auf Deutsch, und so..."
  copyright = "All rights reserved. Copyright samui-samui.de"

  # design elements
  sitecolor = "#d02d19"

#############################################################
# Google Adsense
#############################################################
[params.google]
adclientid = "pub-9026195124322857"

#############################################################
# Search Setup
#############################################################
[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[params.opensearch]
  # https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md

#############################################################
# Search Setup
#############################################################
[params.redirects]
netlify = "https://eloquent-morse-196fd2.netlify.com/"

#############################################################
# Social Media Setup
#############################################################
[params.social.facebook]
  profileid = "517050641"    # patrick.kollitsch
  pageid = "6967849771"      # samuisamui
  appid = "2047624572136513" # samui-samui.de
  profileslug = "patrick.kollitsch"

[params.social.twitter]
  profileid = "davidsneighbour"
  siteid = "samui2"
  theme ="dark"
  linkcolor = "#d02d19"
  dnt = "on"
  csp = "on"

[params.social.snapchat]
  profileid = "pkollitsch"

[params.social.whatsapp]
  profileid = "66878979350"

#############################################################
# DNB Hugo Garuda Setup
#############################################################
[params.dnb]
  theme_slug = "samui-samui"
  javascript = "local-changes.js"
[params.dnb.sidebar]
  enabled = true
  items = [ "author", "archive", "recent", "social" ]
[params.dnb.sidebar.author]
  content = "authorfooter"
[params.dnb.sidebar.recent]
  limit = 5
[params.dnb.sidebar.social]
[params.dnb.sidebar.archive]

[params.dnb.footer.index]
  enabled = true
  items = [ "tagcloud", "leutecloud" ]
[params.dnb.footer.single]
  enabled = false
[params.dnb.footer.tagcloud]
  enabled = true
  type = "cloud"
  values = "tags"

[params.dnb.footer.leutecloud]
  enabled = true
  type = "cloud"
  values = "leute"

[params.dnb.analytics]
  clarity = "3wfl4b6e0x"
