[build]
publish = "public"
command = "./bin/netlify.sh"

[build.environment]
TZ = "Asia/Bangkok"
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"
NODE_VERSION = "16.8.0"
NPM_VERSION = "7.24.1"
GO_VERSION = "1.16.7"
