[build]
  publish = "public/"
  command = "hugo --gc --minify"

[context.production]
  [context.production.environment]
  	TZ = "Asia/Bangkok"
    HUGO_VERSION = "0.55.5"
    HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"
