[build]
  publish = "public/"
  command = ""

[context.production]
  [context.production.environment]
  	TZ = "Asia/Bangkok"
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"
