[build]
publish = "public"
command = "./bin/netlify.sh"

[buildgi.environment]
TZ = "Asia/Bangkok"
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"
NODE_VERSION = "14.14.0"
NODE_ENV = "production"
NPM_VERSION = "6.14.8"
GO_VERSION = "1.15"
