[build]
  publish = "public/"
  # command = "hugo --gc --minify && node scripts/imagemin.js && rm -rf public/posts"
  command = "hugo --gc --minify && rm -rf public/posts"

[build.environment]
  PHP_VERSION="7.2"

[context.production.environment]
  TZ = "Asia/Bangkok"
  HUGO_VERSION = "0.75.1"
  HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  TZ = "Asia/Bangkok"
  HUGO_VERSION = "0.75.1"
  HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"
