[build]
  publish = "public/"
  # command = "hugo --gc --minify && node scripts/imagemin.js && rm -rf public/posts"
  command = "hugo --gc --minify"

[build.environment]
  PHP_VERSION="7.2"

[context.production]
  [context.production.environment]
  	TZ = "Asia/Bangkok"
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"
