[build]
  publish = "public"
  command = ""
  #command = "hugo --gc --minify"

[context.production]
  [context.production.environment]
  	TZ = "Asia/Bangkok"
    HUGO_VERSION = "0.53"
    HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"
