[build]
  publish = "public/"
  # command = "hugo --gc --minify && node scripts/imagemin.js && rm -rf public/posts"
  command = "hugo --gc --minify && rm -rf public/posts"

[build.environment]
  PHP_VERSION="7.2"

[context.production]
  [context.production.environment]
  	TZ = "Asia/Bangkok"
    HUGO_VERSION = "0.58.2"
    HUGO_ENV = "production"
	HUGO_ENABLEGITINFO = "true"

# https://www.netlify.com/docs/netlify-toml-reference/#post-processing
[build.processing]
  skip_processing = true

[context.branch-name.processing]
  skip_processing = false
[context.branch-name.processing.css]
  bundle = true
  minify = true
