################################################################################
# Site parameters
## [params]
################################################################################
# see
# https://gohugo.io/variables/site/#the-siteparams-variable
################################################################################
debug = false
mainSections = ["posts", "post", "blog"]

# social media setup
githubName = ""
og_image = ""
og_image_url = ""

# content particles
copyright = "All rights reserved. Copyright samui-samui.de"
description = "David's Neighbour's Notizen über sein Leben als Auswanderer auf der Insel Koh Samui in Thailand. Auf Deutsch, und so..."
siteslug = "samui-samui-de"

# design elements
sitecolor = "#d02d19"

[author]
# @todo add author information here
################################################################################
# Author setup
## [author]
################################################################################
homepage = "https://kollitsch.de/"
name = "Patrick Kollitsch"

content = "sitewide/authorfooter/index.md"

[author.photo]
name = "patrick-kollitsch.jpg"
title = "Der Autor in seiner natürlichen Umgebung"

[author.format]
layout = "card"
################################################################################

[imaging]
sizes = ["825", "610", "510", "450"]

[opensearch]
# https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md

#############################################################
# Social Media Setup
#############################################################
[social.facebook]
appid = "2047624572136513"        # samui-samui.de
pageid = "6967849771"             # samuisamui
profileid = "517050641"           # patrick.kollitsch
profileslug = "patrick.kollitsch"

[social.twitter]
csp = "on"
dnt = "on"
linkcolor = "#d02d19"
profileid = "davidsneighbour"
siteid = "samui2"
theme = "dark"

[social.snapchat]
profileid = "pkollitsch"

[social.whatsapp]
profileid = "66878979350"

#############################################################
# DNB Hugo Garuda Setup
#############################################################
[dnb]
copy-from = "2005"
javascript = "local-changes.js"
theme_slug = "samui-samui"

[dnb.sidebar]
enabled = true
items = ["author", "archive", "recent", "social"]
[dnb.sidebar.author]
content = "authorfooter"
[dnb.sidebar.recent]
limit = 5
[dnb.sidebar.social]
[dnb.sidebar.archive]
[dnb.sidebar.radio]
spotify_playlist = "https://open.spotify.com/embed/playlist/7DEuLS0qC7ajP84kEuWw6H"

[dnb.footer.index]
enabled = true
items = ["tagcloud", "leutecloud"]
[dnb.footer.single]
enabled = false
[dnb.footer.tagcloud]
enabled = true
type = "cloud"
values = "tags"

[dnb.footer.leutecloud]
enabled = true
type = "cloud"
values = "leute"

[dnb.comments]
#repo = "davidsneighbour/samui-samui.de.comments"
# src = "https://utteranc.es/client.js"
# term = "pathname"
# label = "💬"
# theme = "github-dark-orange"

################################################################################
# hugo-head @see https://github.com/davidsneighbour/hugo-head
################################################################################
[dnb.head]
charset = "utf-8"
latitude = "9.578492"
longitude = "99.958311"
viewport = "width=device-width, initial-scale=1"
# https://en.wikipedia.org/wiki/ISO_3166
disable = []
notranslate = false     # tell Google not to provide a translation for this document
placename = "Koh Samui"
region = "TH-84"
separator = " ↭ "
# https://webmonetization.org/docs/getting-started
monetization = ""

[dnb.head.speedoptimisation]
control = "on" # on/off - off disables all prefetching
preconnect = []
prefetch = [
  "/assets/webfonts/tomkin/Tomkin/TomkinLight/Tomkin-Light.woff",
  "/assets/webfonts/tomkin/Tomkin/TomkinSemiLight/Tomkin-SemiLight.woff",
]
prerender = []

[dnb.head.verification]
alexa = ""
bing = ""
google = ""
norton = ""
pinterest = ""
yandex = ""

[dnb.head.styles]
method = "postcss"

[dnb.head.styles.options]
# options for the compilation of CSS
# see https://gohugo.io/hugo-pipes/scss-sass/#options
#transpiler = "dartsass"
enableSourceMap = true
includePaths = ["node_modules/"]
outputStyle = "compressed"
targetPath = "theme.css"

[dnb.forms]
[dnb.forms.contactform]
groups = true
groupstyle = 'grid'
id = 'contactform'
labelling = 'i18n'

[dnb.forms.contactform.attributes]
class = 'mb-6'
data-netlify = 'true'
netlify-honeypot = '%random%'

[dnb.forms.contactform.fields]
[[dnb.forms.contactform.fields.1]]
label = 'shortcodes.form.name'
name = 'shortcodes.form.fieldnames.name'
required = true
type = 'text'
[[dnb.forms.contactform.fields.1]]
html = '<div data-netlify-recaptcha="true"></div>'
type = 'special'
[[dnb.forms.contactform.fields.1]]
name = '%random%'
type = 'invisible'
[[dnb.forms.contactform.fields.2]]
label = 'shortcodes.form.message'
name = 'shortcodes.form.fieldnames.message'
required = true
type = 'textarea'
[dnb.forms.contactform.fields.2.options]
rows = 8
[[dnb.forms.contactform.buttons]]
class = 'btn btn-primary'
label = 'shortcodes.form.submit'
name = 'shortcodes.form.fieldnames.submit'
type = 'submit'

[dnb.shortcodes.pagefind]
showImages = false

[dnb.hooks]
[[dnb.hooks.items.kollitsch.head-end]]
cached = true
file = "head-end-matomo"

# netlification - @see https://dnbhub.xyz/netlification
################################################################################
[dnb.netlification]
extensions = ["youtube", "cloudflare.insights"]
mode = "netlify"
upgradeInsecureRequests = true

[dnb.netlification.csp]
reportOnly = false
# reportUri = ""

#require-trusted-types-for = ["'script'"]
base-uri = ["'self'"]
child-src = ["'self'"]
connect-src = [
  "'self'",
  'https://analytics.dnbhub.xyz/',
  "https://api.github.com/",
  'cloudflareinsights.com',
]
default-src = ["'self'"] # @todo move to 'none' after fixing all issues
font-src = ["'self'", "https://d33wubrfki0l68.cloudfront.net"]
form-action = ["'self'", "https://formspree.io/f/xoqyzooe"]
frame-ancestors = ["'self'"]
frame-src = [
  "'self'",
  "https://open.spotify.com/",
  "https://giscus.app/",
  "https://www.youtube-nocookie.com",
]
img-src = [
  "'self'",
  "data:",
  'https://analytics.dnbhub.xyz/',
  "https://d33wubrfki0l68.cloudfront.net",
  "https://lite-vimeo-embed.now.sh",
  "https://lite-vimeo-embed.vercel.app",
  "ytimg.googleusercontent.com",
  "https://i.ytimg.com",
]
manifest-src = ["'self'"]
media-src = ["'self'"]
object-src = ["'none'"]
script-src = [
  "'self'",
  "'unsafe-eval'",
  "'unsafe-inline'",
  "'wasm-unsafe-eval'",
  "https://d33wubrfki0l68.cloudfront.net",
  "https://giscus.app/",
  'https://unpkg.com',
  "https://identity.netlify.com",
  "static.cloudflareinsights.com",
  'https://analytics.dnbhub.xyz/',
]
style-src = [
  "'self'",
  "'unsafe-inline'",
  "https://d33wubrfki0l68.cloudfront.net",
  "https://giscus.app/",
]
upgradeInsecureRequests = true
worker-src = ["'self'"]

[[dnb.netlification.redirects]]
netlify = "https://samui-samui-de.netlify.app/"
