################################################################################
# Site setup
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://192.168.1.201:1313/" # hostname & path to the root
defaultContentLanguage = "de" 
disableHugoGeneratorInject = true # we do that proudly on each page in the footer. visible.
disableKinds = [] 
enableEmoji = true # see https://www.webfx.com/tools/emoji-cheat-sheet/
# dev: check https://discourse.gohugo.io/t/differing-pages-between-dev-and-production/28270
#    before enabling this.
enableGitInfo = false # Enable GitInfo feature
enableRobotsTXT = true # Build robots.txt file
footnoteAnchorPrefix = "#" 
footnoteReturnLinkContents = "^" 
languageCode = "de_DE" 
languageName = "Deutsch" 
refLinksErrorLevel = "WARNING" 
refLinksNotFoundURL = "/404.html" 
relativeURLs = true # makes all relative urls absolute to root... yeah, don't ask. we won't tell...
rssLimit = 10 
summaryLength = 150 # the length of text to show in a .Summary
title = "Samui? Samui!" 

################################################################################
# Bugfixes and Troubleshooting
################################################################################
# workaround for a weird time out error on netlify
# "Error building site: $FILENAME: timed out initializing value. This is most
# likely a circular loop in a shortcode"
#timeout = 100000000000000

# @todo fix the issue instead of the warning
ignoreLogs = ['warning-goldmark-raw-html']
